### ISSUE TITLE
[Bug]: 运行时报错

### ISSUE THREAD

**Issue by wym19970515** [1umine/go-cqhttp#3]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

f16d72f

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad

### 重现步骤

疑似是定时任务导致的报错

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

报错停止

### 日志记录（可选）

```golang
gocq端：
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x80ea23]

goroutine 71 [running]:
github.com/Mrs4s/go-cqhttp/cmd/gocq.signStartRefreshToken(0x28)
        github.com/Mrs4s/go-cqhttp/cmd/gocq/qsign.go:400 +0x323
created by github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:172 +0x545

nonebot端：
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
random_group_push: There are no bots to get.
random_group_push: Traceback (most recent call last):
  File "E:\PythonProject\QQRobot\myQQRobot\src\plugins\gen_pic_by_word.py", line 769, in random_group_push
    bot = get_bot()
  File "E:\PythonProject\QQRobot\venv\lib\site-packages\nonebot\__init__.py", line 156, in get_bot
    raise ValueError("There are no bots to get.")
ValueError: There are no bots to get.
```

### 补充说明（可选）

![image](https://github.com/1umine/go-cqhttp/assets/45259608/a4b180aa-85cb-4638-9d95-fc3a73441784)
![image](https://github.com/1umine/go-cqhttp/assets/45259608/1dd62ff3-0587-4415-b132-77f1311a30a7)
![image](https://github.com/1umine/go-cqhttp/assets/45259608/b6c4d7d7-b584-4ec0-a7b3-8e042ce2a468)

**Comment by 1umine** [comment]
这是上游分支的 bug，我这没有此 bug。不想等官方修复可以自行修改代码重新编译，参照 https://github.com/Mrs4s/go-cqhttp/issues/2437 修改源码。或者用我这最近几个 action 的构建的
